print("Welcome to Git tutorial!")
print("Welcome to learning git and github")
print("I appreciete to learning git and github")
print("Python to learning git and github")
print("To learning git and github")
